alias e='vim ~/.zshrc'
alias s='source ~/.zshrc'
alias jc='jupyter console'
alias epoch='date +%s%3N'
alias now='date --rfc-3339=ns'
alias passgen='cat /dev/urandom | head -c24 | md5sum | cut -d " " -f1 | tr -d $"\n"'
alias macgen='echo -n 02; od -t x1 -An -N 5 /dev/urandom | tr " " ":"'
alias terminal-theme-dark='cat /home/wls/Projects/Personal/conf/gnome-terminal-dark.dconf | dconf load /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/'
alias terminal-theme-light='cat /home/wls/Projects/Personal/conf/gnome-terminal-light.dconf | dconf load /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/'

abbr -S -g --force --quiet xclp='xclip -selection c'
