alias lk='KUBECONFIG=.kube-config kubectl'

abbr -S -g --force --quiet k='kubectl'
abbr -S -g --force --quiet ksys='kubectl -n kube-system'
abbr -S -g --force --quiet kdev='kubectl -n develop'
abbr -S -g --force --quiet ktest='kubectl -n test'
abbr -S -g --force --quiet kspo='kubectl -n sport'
abbr -S -g --force --quiet kspob='kubectl -n sport-beta'
abbr -S -g --force --quiet kspoa='kubectl -n sport-alpha'
abbr -S -g --force --quiet kdis='kubectl -n discovery'
abbr -S -g --force --quiet kair='kubectl -n airflow'
abbr -S -g --force --quiet kaut='kubectl -n autotests'
abbr -S -g --force --quiet kmon='kubectl -n monitoring'
abbr -S -g --force --quiet kpay='kubectl -n payment'
abbr -S -g --force --quiet kst='kubectl -n staging'
abbr -S -g --force --quiet kist='kubectl -n istio-system'
abbr -S -g --force --quiet ksc='kubectl config use-context'
abbr -S -g --force --quiet kgc='kubectl config get-contexts'
abbr -S -g --force --quiet ksn="kubectl config set-context --current --namespace \"\$(kubectl get ns | fzf | cut -d ' ' -f1 | xargs)\""
